Nop.Plugin.Payments.Uniteller/Controllers/PaymentUnitellerController.cs
using System;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Plugin.Payments.Uniteller.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.Uniteller.Controllers
{
    public class PaymentUnitellerController : BasePaymentController
    {
        private readonly ILocalizationService _localizationService;
        private readonly ILogger _logger;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly IPaymentService _paymentService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IWebHelper _webHelper;
        private readonly INotificationService _notificationService;
        private readonly IPaymentPluginManager _paymentPluginManager;

        public PaymentUnitellerController(ILocalizationService localizationService,
            ILogger logger,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            IPaymentService paymentService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            IWebHelper webHelper,
            INotificationService notificationService,
            IPaymentPluginManager paymentPluginManager)
        {
            _localizationService = localizationService;
            _logger = logger;
            _orderProcessingService = orderProcessingService;
            _orderService = orderService;
            _paymentService = paymentService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _webHelper = webHelper;
            _notificationService = notificationService;
            _paymentPluginManager = paymentPluginManager;
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var unitellerPaymentSettings = await _settingService.LoadSettingAsync<UnitellerPaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                ShopIdp = unitellerPaymentSettings.ShopIdp,
                Login = unitellerPaymentSettings.Login,
                Password = unitellerPaymentSettings.Password,
                AdditionalFee = unitellerPaymentSettings.AdditionalFee,
                AdditionalFeePercentage = unitellerPaymentSettings.AdditionalFeePercentage,
                ActiveStoreScopeConfiguration = storeScope
            };

            if (storeScope > 0)
            {
                model.ShopIdpOverrideForStore = await _settingService.SettingExistsAsync(unitellerPaymentSettings, x => x.ShopIdp, storeScope);
                model.LoginOverrideForStore = await _settingService.SettingExistsAsync(unitellerPaymentSettings, x => x.Login, storeScope);
                model.PasswordOverrideForStore = await _settingService.SettingExistsAsync(unitellerPaymentSettings, x => x.Password, storeScope);
                model.AdditionalFeeOverrideForStore = await _settingService.SettingExistsAsync(unitellerPaymentSettings, x => x.AdditionalFee, storeScope);
                model.AdditionalFeePercentageOverrideForStore = await _settingService.SettingExistsAsync(unitellerPaymentSettings, x => x.AdditionalFeePercentage, storeScope);
            }

            return View("~/Plugins/Payments.Uniteller/Views/Configure.cshtml", model);
        }
        
        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var unitellerPaymentSettings = await _settingService.LoadSettingAsync<UnitellerPaymentSettings>(storeScope);

            //save settings
            unitellerPaymentSettings.ShopIdp = model.ShopIdp;
            unitellerPaymentSettings.Login = model.Login;
            unitellerPaymentSettings.Password = model.Password;
            unitellerPaymentSettings.AdditionalFee = model.AdditionalFee;
            unitellerPaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
             await _settingService.SaveSettingOverridablePerStoreAsync(unitellerPaymentSettings, x => x.ShopIdp, model.ShopIdpOverrideForStore, storeScope, false);
             await _settingService.SaveSettingOverridablePerStoreAsync(unitellerPaymentSettings, x => x.Login, model.LoginOverrideForStore, storeScope, false);
             await _settingService.SaveSettingOverridablePerStoreAsync(unitellerPaymentSettings, x => x.Password, model.PasswordOverrideForStore, storeScope, false);
             await _settingService.SaveSettingOverridablePerStoreAsync(unitellerPaymentSettings, x => x.AdditionalFee, model.AdditionalFeeOverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(unitellerPaymentSettings, x => x.AdditionalFeePercentage, model.AdditionalFeePercentageOverrideForStore, storeScope, false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

           _notificationService. SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return RedirectToAction("Configure");
        }
        
        private ContentResult GetResponse(string textToResponse, bool success = false)
        {
            var msg = success ? "SUCCESS" : "FAIL";
            if (!success)
                _logger.ErrorAsync($"Uniteller. {textToResponse}");
           
            return Content($"{msg}\r\nnopCommerce. {textToResponse}", "text/plain", Encoding.UTF8);
        }

        private string GetValue(string key, IFormCollection form)
        {
            return (form.Keys.Contains(key) ? form[key].ToString() : _webHelper.QueryString<string>(key)) ?? string.Empty;
        }

        private async Task<IActionResult> UpdateOrderStatus(Order order, string status)
        {
            status = status.ToUpper();
            var textToResponse = "Your order has been paid";

            switch (status)
            {
                case "CANCELED":
                {
                    //mark order as canceled
                    if ((order.PaymentStatus == PaymentStatus.Paid || order.PaymentStatus == PaymentStatus.Authorized) &&
                        _orderProcessingService.CanCancelOrder(order))
                            await _orderProcessingService.CancelOrderAsync(order, true);

                    textToResponse = "Your order has been canceled";
                }
                    break;
                case "AUTHORIZED":
                {
                    //mark order as authorized
                    if (_orderProcessingService.CanMarkOrderAsAuthorized(order))
                            await _orderProcessingService.MarkAsAuthorizedAsync(order);
                    textToResponse = "Your order has been authorized";
                }
                    break;
                case "PAID":
                {
                    //mark order as paid
                    if (_orderProcessingService.CanMarkOrderAsPaid(order) && status.ToUpper() == "PAID")
                            await _orderProcessingService.MarkOrderAsPaidAsync(order);
                }
                    break;
                default:
                {
                    return GetResponse("Unsupported status");
                }
            }

            return GetResponse(textToResponse, true);
        }

        public async Task<IActionResult> ConfirmPay(IFormCollection form)
        {
            var processor =
              await _paymentPluginManager.LoadPluginBySystemNameAsync("Payments.Uniteller") as UnitellerPaymentProcessor;
            if (processor == null ||
                !_paymentPluginManager.IsPluginActive(processor) || !processor.PluginDescriptor.Installed)
                throw new NopException("Uniteller module cannot be loaded");

            const string orderIdKey = "Order_ID";
            const string signatureKey = "Signature";
            const string statuskey = "Status";

            var orderId = GetValue(orderIdKey, form);
            var signature = GetValue(signatureKey, form);
            var status = GetValue(statuskey, form);

            Order order = null;

            if (Guid.TryParse(orderId, out Guid orderGuid))
            {
                order = await _orderService.GetOrderByGuidAsync(orderGuid);
            }

            if (order == null)
                return GetResponse("Order cannot be loaded");

Nop.Plugin.Payments.Uniteller/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}
@model Nop.Plugin.Payments.Uniteller.Models.ConfigurationModel

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentUniteller" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <p>
                    <b>If you're using this gateway ensure that your primary store currency is supported by Uniteller</b><br />
                    <b>For plug-in configuration, you must perform the following actions:</b>
                    <ul>
                        <li>Sign up on the website uniteller.ru</li>
                        <li>Sign in to your personal cabinet</li>
                        <li>Fill out the field «Uniteller Point ID» (Menu item «Sales points»), "Login" and «Password» (Menu item « Authorization parameters »)</li>
                        <li>Specify the URL-address notification to the store like http://www.yourStore.com/Plugins/Uniteller/ConfirmPay on the edit page of the point of sale</li>
                    </ul>
                </p>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ShopIdpOverrideForStore" asp-input="ShopIdp" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ShopIdp" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ShopIdp" />
                        <span asp-validation-for="ShopIdp"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="LoginOverrideForStore" asp-input="Login" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Login" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Login" />
                        <span asp-validation-for="Login"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PasswordOverrideForStore" asp-input="Password" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Password" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeeOverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentageOverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        &nbsp;
                    </div>
                    <div class="col-md-9">
                        <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.Uniteller/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.Uniteller.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>